name: sati_user_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  font_awesome_flutter: ^9.0.0
  animated_text_kit: ^4.2.1
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.2
  cloud_firestore: ^1.0.7
  firebase_storage: ^8.0.5
  image_picker: ^0.7.4
  flutter_native_splash: ^1.1.8+4
  universal_html: ^2.0.8

flutter_native_splash:
  color: "FFFFFF"
  android: true
  ios: true
  web: true
  image: assets/SATILogo.png

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true  
  assets:
    - assets/
  fonts:
    - family: fredoka
      fonts:
        - asset: fonts/FredokaOne-Regular.ttf
    - family: Coda
      fonts:
        - asset: fonts/CodaCaption-ExtraBold.ttf
    - family: Pacific
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Crimson
      fonts:
        - asset: fonts/CrimsonText-Regular.ttf
    - family: PT
      fonts:
        - asset: fonts/PTSans-Regular.ttf